### ISSUE TITLE
KeyError during Initialization of Spatial Matrix

### ISSUE THREAD

**Issue by cjgabrie** [denisecailab/minian#119]
I've encountered a new error while running the pipeline since the update last weekend. I am getting a KeyError when trying to initialize the spatial matrix after successful seed refinement pointing me to issues with the 'height' index, but I can't see any issues. I'm running a PC with Windows 10 and using Minian from an Anaconda environment. I've included images of the parameters I'm using up until that point, a look at the state of 'seeds_final' and 'varr' at the point I'm getting the error, and images from the error itself. Do you have any suggestions of how to fix this problem?

Parameters:
![initA_issue_params](https://user-images.githubusercontent.com/25350601/114589184-4ab0be80-9c3c-11eb-81f2-1c7972b656c7.jpg)

varr & seeds_final:
![varr_seedsfinal](https://user-images.githubusercontent.com/25350601/114589518-995e5880-9c3c-11eb-9dbf-c1181176cdf3.jpg)

![varr_seedsfinal_height](https://user-images.githubusercontent.com/25350601/114589527-9bc0b280-9c3c-11eb-8e68-b5094bbb7af9.jpg)

KeyError Stack:
![minianInitA_1](https://user-images.githubusercontent.com/25350601/114589557-a3805700-9c3c-11eb-964f-bb41b4c77f5e.jpg)

![minianInitA_2](https://user-images.githubusercontent.com/25350601/114589571-a54a1a80-9c3c-11eb-92f9-94c3f7bca246.jpg)

**Comment by phildong** [comment]
this seem to be caused by using `subset`. A fix is being worked on here: #124
