### ISSUE TITLE
Incompatibility new release jinja2 

### ISSUE THREAD

**Issue by AlexLM96** [denisecailab/minian#197]
First time minian user! I was trying to do a fresh install and follow the pipeline for the demo videos.

When running the "import minian" cell, I ran into an "Import Error" for importing Markup from jinja2 (this new release is quite
recent). 

It seems like there is some incompatibility between the Bokeh and Panel version that is installed by default using the suggested "conda install -y -c conda-forge minian" and the jinja2 version. See: 

https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-1
https://github.com/holoviz/panel/releases , https://github.com/holoviz/panel/issues/3257

I tried installing panel before minian, but the latest of panel requires python 3.10, and minian requires python >=3.8, <3.9, so I'm running into some compatibility issues this way too. 

Could you provide a list of the packages versions that do not have any incompatibilities including jinja2  (or possibly have the conda installer default to compatible versions)?

**Comment by ckemere** [comment]
It looks like v. 3.0.3 may work. I've gotten past that block by installing it `conda install jinja2=3.0.3`.

**Comment by hardawayja** [comment]
Hi,

We have also had to roll it back to get it to work. `conda install jinja2=2.11.2` Working fine now!
`

**Comment by phildong** [comment]
Thanks a lot for the info! I'll put in PR shortly to address this!
