### ISSUE TITLE
Pre-Batch for individual ROI using in motion correction 

### ISSUE THREAD

**Issue by susiefeng** [DeniseCaiLab/minian#20]
Having a separate pre-batch notebook file for users who wants to select ROI for every video will be helpful! Especially when imaging is not clean which have dirts on either lens or miniscope. Generate an output file for ROI info in each folder, if users don't need to set different ROIs for their videos (don't have that ROI info file in the video folder), can automatically use the default for motion correction.

**Comment by phildong** [comment]
implemented in 3856b3d9aacd83b5c23975c48a0c4f0a20ab84e4. Please give it a try and let me know if it works.

**Comment by phildong** [comment]
feel free to re-open if previous comment hasn't solve the problem
