### ISSUE TITLE
ROI Selection for Motion Correction Has a Non-int in dict issue

### ISSUE THREAD

**Issue by susiefeng** [DeniseCaiLab/minian#23]
Currently the **Estimate Shift** part doesn't work because the slice info for height and width are not integer. 
The subset_mc looks like this right now:
![float](https://user-images.githubusercontent.com/47085209/53539076-20442b80-3ade-11e9-8bdd-7232c8267101.PNG)
But I guess it needs to look like this for **Estimate Shift** to work:
![int](https://user-images.githubusercontent.com/47085209/53539100-3651ec00-3ade-11e9-8be0-0773dbe7e349.PNG)

But I don't know how to change thing in a dictionary to int type..
![setroi](https://user-images.githubusercontent.com/47085209/53539121-4e297000-3ade-11e9-938e-288f381bd4d3.PNG)

Error looks like this:
![estimate](https://user-images.githubusercontent.com/47085209/53539311-11aa4400-3adf-11e9-8d17-16abd6bb58a2.PNG)

**Comment by phildong** [comment]
should be fixed in current version.
