### ISSUE TITLE
Adding references in Shifted Target and Template in cross-registration and motion correction

### ISSUE THREAD

**Issue by susiefeng** [DeniseCaiLab/minian#24]
In the alignment part for cross-registration, it will be helpful to add some reference in **Shifted Target** window as well. Users can easily tell if their alignment works well! 
Same idea for visualizing how good the video has been motion corrected after motion correction.
![cross-reg box](https://user-images.githubusercontent.com/47085209/53822690-39b20100-3f3e-11e9-90bf-ddb6c754fa3d.PNG)

**Comment by wmau** [comment]
`dev` now has a good visualization with using maximum projections pre- and post-motion correction.
