### ISSUE TITLE
VArrayViewer not displaying video, but a frozen frame. 

### ISSUE THREAD

**Issue by anna-teruel** [denisecailab/minian#251]
Hey! I've been using minian for a while and always worked perfectly. However, I've been trying to install it in a macos M1 with arm64 architecture, and although I can install it correctly, when I open my jupyter notebook and try to visualize raw data, it looks like my video is "frozen" and VArrayViewer shows only one frame. My 'varr' frame: 3000height: 600width: 600. 

For installation, I cloned repository and run "pip install .", then I installed "pip install markupsafe==2.0" because it was desplying an error when tried to run "jupyter notebook". Although my mac has arm64, miniconda I have installed is 'macOS-10.16-x86_64-i386-64bit', which is compatible with minian. 

In my environment, I have following packages installed. Perhaps it's an incompatibility issue? 
anyio                     4.0.0
appnope                   0.1.3
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asciitree                 0.3.3
asttokens                 2.4.0
attrs                     23.1.0
backcall                  0.2.0
beautifulsoup4            4.12.2
bleach                    6.0.0
bokeh                     1.4.0
certifi                   2023.7.22
cffi                      1.16.0
cftime                    1.6.2
click                     8.1.7
cloudpickle               2.2.1
colorcet                  3.0.1
comm                      0.1.4
contourpy                 1.1.1
cvxpy                     1.3.2
cycler                    0.12.0
dask                      2021.2.0
datashader                0.12.1
datashape                 0.5.2
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
distributed               2021.2.0
ecos                      2.0.12
entrypoints               0.4
exceptiongroup            1.1.3
executing                 2.0.0
fasteners                 0.19
fastjsonschema            2.18.1
ffmpeg-python             0.2.0
fonttools                 4.43.0
fqdn                      1.5.1
fsspec                    2023.9.2
future                    0.18.3
holoviews                 1.12.7
idna                      3.4
imageio                   2.31.5
importlib-metadata        6.8.0
importlib-resources       6.1.0
ipykernel                 6.25.2
ipython                   8.12.3
ipython-genutils          0.2.0
ipywidgets                8.1.1
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    2.11.3
joblib                    1.3.2
jsonpointer               2.4
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
jupyter                   1.0.0
jupyter_client            7.4.9
jupyter-console           6.6.3
jupyter_core              5.3.2
jupyter-events            0.7.0
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyterlab-pygments       0.2.2
jupyterlab-widgets        3.0.9
kiwisolver                1.4.5
llvmlite                  0.35.0
locket                    1.0.0
Markdown                  3.4.4
MarkupSafe                2.0.0
matplotlib                3.7.3
matplotlib-inline         0.1.6
MedPy                     0.4.0
minian                    1.2.1
mistune                   0.8.4
msgpack                   1.0.7
multipledispatch          1.0.0
natsort                   8.4.0
nbclassic                 1.0.0
nbclient                  0.5.13
nbconvert                 6.4.5
nbformat                  5.9.2
nest-asyncio              1.5.8
netCDF4                   1.6.4
networkx                  2.4
notebook                  6.5.6
notebook_shim             0.2.3
numba                     0.52.0
numcodecs                 0.11.0
numpy                     1.20.2
opencv-python             4.2.0.34
osqp                      0.6.3
overrides                 7.4.0
packaging                 23.2
pandas                    1.2.3
pandocfilters             1.5.0
panel                     0.8.0
param                     1.13.0
parso                     0.8.3
partd                     1.4.1
patsy                     0.5.3
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    10.0.1
pip                       23.2.1
pkgutil_resolve_name      1.3.10
platformdirs              3.10.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
psutil                    5.9.5
ptyprocess                0.7.0
pure-eval                 0.2.2
pycparser                 2.21
pyct                      0.5.0
pyFFTW                    0.12.0
Pygments                  2.16.1
PyMetis                   2020.1
pyparsing                 3.1.1
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2023.3.post1
pyviz_comms               3.0.0
PyWavelets                1.4.1
PyYAML                    6.0.1
pyzmq                     24.0.1
qdldl                     0.1.7.post0
qtconsole                 5.4.4
QtPy                      2.4.0
rechunker                 0.3.3
referencing               0.30.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.3
scikit-image              0.18.1
scikit-learn              0.22.1
scipy                     1.10.1
scs                       3.2.3
Send2Trash                1.8.2
setuptools                68.2.2
SimpleITK                 2.0.2
six                       1.16.0
sk-video                  1.1.10
sniffio                   1.3.0
sortedcontainers          2.4.0
soupsieve                 2.5
sparse                    0.11.2
stack-data                0.6.3
statsmodels               0.14.0
tblib                     2.0.0
terminado                 0.17.1
testpath                  0.6.0
tifffile                  2023.7.10
toolz                     0.12.0
tornado                   6.3.3
tqdm                      4.66.1
traitlets                 5.10.1
types-python-dateutil     2.8.19.14
typing_extensions         4.8.0
uri-template              1.3.0
wcwidth                   0.2.8
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.3
wheel                     0.41.2
widgetsnbextension        4.0.9
xarray                    0.17.0
zarr                      2.16.1
zict                      3.0.0
zipp                      3.17.0

Please, find attached a video of what I see on my jupyter notebook. I have also tried to open jupyter with different browsers (safari and crhome), but error persist. 

https://github.com/denisecailab/minian/assets/78961609/2393ebd1-06bd-4866-ad99-1ebc68b52985

I have tried with several videos. The one I am attaching is a video I analyzed a while ago, so I know the file is correct. 

I don't know how to solve this issue, because I don't understand what's wrong. If anybody knows and could help, I would appreciate it. 

Thanks!!

**Comment by Owenxz** [comment]
Hi, I had the same issue on linux, and downgrading pyviz_comms solved it as suggested by this post https://github.com/denisecailab/minian/issues/249#issue-1849967897

**Comment by anna-teruel** [comment]
Great! It was that. I downgraded it to **pyviz_comms==2.0.2** and solved the problem.
Thanks @Owenxz !!!!
