### ISSUE TITLE
Markup and Jinja2 Error 

### ISSUE THREAD

**Issue by skisurfer13** [denisecailab/minian#269]
Hello! I'm getting the following error when running the third cell of the Minian pipeline:

`ImportError: cannot import name 'Markup' from 'jinja2'`

I believe we were having this error a couple of years ago as well, however it was subsequently resolved. I've been using Minian for a few months now and this is a new error for me, never happened in previous iterations of the pipeline. 

I tried the approaches used previously in #197 and #206 however I'm running into compatibility issues there as well. 

Thank you!

**Comment by austinbaggetta** [comment]
I just want to post here on how we fixed this issue for future reference:

From this stackoverflow post (https://stackoverflow.com/questions/71645272/importerror-cannot-import-name-markup-from-jinja2) it may potentially be a Flask issue. Minian does not pin Flask, so you may have to remove Flask and downgrade to an older version (such as 2.0.3 used in the post).

Downgrading Flask fixed the issue.
