### ISSUE TITLE
Update Motion Correction 

### ISSUE THREAD

**Issue by susiefeng** [DeniseCaiLab/minian#28]
Right now, the select roi for motion correction step is not matching with the later on code, need to be update!
![mc1](https://user-images.githubusercontent.com/47085209/55369675-8e0cba00-54c5-11e9-85c2-c1a0843cf5b9.PNG)
![mc2](https://user-images.githubusercontent.com/47085209/55369679-91a04100-54c5-11e9-8e76-bc3b29f4e12d.PNG)

**Comment by phildong** [comment]
should be fixed in current version
