### ISSUE TITLE
Newer cvxpy version has compatibility issues.

### ISSUE THREAD

**Issue by ZachPenn** [DeniseCaiLab/minian#33]
Latest version of cvxpy (1.0.24) results in error during `import minian`.  Explicit download of v1.0.1 resolves issue.  You may want to either explicitly put version control in .yml file or resolve compatibility issue with latest version.

**Comment by phildong** [comment]
Could you provide more information on the error so I could try to look into this? I'm not sure explicitly specifying an older version is an ideal solution, but if it's something with conda's build we could put `cvxpy` under `pip` which would also get rid of the additional windows steps

**Comment by phildong** [comment]
can you confirm the issue you are seeing is described here: https://github.com/cvxgrp/cvxpy/issues/514 and https://github.com/cvxgrp/cvxpy/issues/677 ?
If so we can enforce an older version for now in `master`, but we should probably consider switching to pip in the future

**Comment by phildong** [comment]
should be fixed by 27fd26347d761c17140bc9f3f95abd805397a64d. 1.0.1 of `cvxpy` doesn't have a windows build on conda, and using `pip` seems to make conda unhappy and result in "inconsistency". Feel free to re-open if the issue persists.
