### ISSUE TITLE
VArrayViewer compute variable

### ISSUE THREAD

**Issue by GarrettBlair** [DeniseCaiLab/minian#35]
Just downloaded a more recent version of minian, it seems that the "compute" argument has been removed from the VArrayViewer, but the pipelines still pass "compute=True" as an argument

**Comment by GarrettBlair** [comment]
* in minian/visualization.py

**Comment by phildong** [comment]
Thanks a lot! this should be fixed in `dev` branch, I'll keep you posted once that makes into `master`

**Comment by wmau** [comment]
Closed due to inactivity.
