### ISSUE TITLE
Spike Trains from the output files

### ISSUE THREAD

**Issue by ForoughHa** [DeniseCaiLab/minian#50]
Dear all,

This is more of a question rather than an issue that I wanted to ask you.
About the demo dataset, is it correct that we are using 10 recording files each having 1000 frames? And then we concatenate them all to form a complete recording session? If this is the case, shouldn't we expect to have **10 * 1000 = 10000** frames in our output processed files?  Why is it that I only get 2000 frames in the output files?

Finally, since for my analysis, I am interested in spike trains from neurons, I want to use the _S_temporal_it2_ and then extract spike trains (e.g. a time series for each neuron/unit which states the times when a spike happens). So I want to get a single vector for each neuron which tells me when a spike happens. When I try to see what is stored in _S_temporal_it2_, I get:

<img width="1121" alt="Screen Shot 2020-04-19 at 4 37 40 pm" src="https://user-images.githubusercontent.com/34736867/79681447-b21c7400-825d-11ea-956e-5de2275344fd.png">

And now I go back to my first question. Why is it that it shows only 2000 frames? I also see only 2000 frames in the plots of the last step in the pipeline. Am I missing something that I think we should get more frames from 10 recordings of 1000 frames? Similarly, Why do we only have a vector of length 1000 in **S** for each of 359 units extracted from demo videos? Shouldn't it be longer than that since we have concatenated 10 videos of each 1000 frames?

Also, could you please explain to me a bit about what is actually stored in this variable? What are the numbers in the array representative of? and **can I get the spike trains (as I explained) from this pipeline and these saved variables?** Should I be looking for all the local maxima in the rows of **S** each corresponding to a unit? 
Thank you very much in advance for taking the time.

**Comment by cineguerrilha** [comment]
the example movies do not have 1000 frames each
