### ISSUE TITLE
In pipeline.ipynb import minian error: 'Module not Found'

### ISSUE THREAD

**Issue by MartoMandelbaum** [DeniseCaiLab/minian#57]
Hello, I've encountered this error message while attempting to run the 'Import minian' section: ModuleNotFoundError: No module named 'sklearn.externals.joblib'

<img width="1092" alt="Screen Shot 2020-05-26 at 16 18 08" src="https://user-images.githubusercontent.com/65977275/82941397-a7e04a80-9f6c-11ea-8ae3-f83613266083.png">
<img width="1015" alt="Screen Shot 2020-05-26 at 16 19 38" src="https://user-images.githubusercontent.com/65977275/82941498-d3fbcb80-9f6c-11ea-8a44-b7357509d070.png">

**Comment by wmau** [comment]
@MartoMandelbaum can you report your sklearn package version using `conda list -n minian scikit-learn`?

**Comment by MartoMandelbaum** [comment]
sure thing, it says scikit-learn version  0.23.1    (Build :py37hf5857e7_0 , Channel: conda-forge)

**Comment by wmau** [comment]
@MartoMandelbaum looks like they deprecated `sklearn.externals.joblib` in 0.23. Can you try `conda install -n minian scikit-learn=0.22` and try again?

**Comment by MartoMandelbaum** [comment]
@wmau no error this time, it appears to run smoothly. Thanks for the solution.

**Comment by wmau** [comment]
Great, glad to help!
