### ISSUE TITLE
Highlight documentation/notes to give user a hint what they should do besides of simply running through the pipeline

### ISSUE THREAD

**Issue by susiefeng** [DeniseCaiLab/minian#6]
It can be more user friendly (especially for people don't have much coding background) if there are highlight parts of note to tell user what they should be doing right now before starting run the next cell of code. 

e.g: 
1: a line of highlighted note saying: **set dpath to the folder contains the recordings** before the dpath setting part. Same thing, in batch processing, this line can be: ** set dpath to the master folder that contains all the recordings of animals/sessions you want to batch process here, number of folder layers doesn't matter.'**

2: a line of highlighted note saying: **Applying the updated parameters to param_xxx now, for example, you can do: param_seeds_merger['thres_corr']=0.7 to apply the new parameter value.** This line of note can locate after the parameter exploring part, and right before going into real updates.

**Comment by phildong** [comment]
implemented in a9e5c37a712b1aba801eaf0441838ecb421153f4
