### ISSUE TITLE
Error with cross-registration

### ISSUE THREAD

**Issue by cliu-vassar** [DeniseCaiLab/minian#61]
Hi, I've been working with some of the datasets that I ran through the main pipeline, and I keep running into an error in the visualizing overlapping cells step in the cross-registration notebook.
![image](https://user-images.githubusercontent.com/60406457/84670155-be3a5000-aef3-11ea-9e7b-ce414850fa62.png)

**Comment by eforbes24** [comment]
I'm also getting this error running cross-registration in a python script (not the jupyter notebook), has anyone found a fix?

**Comment by wmau** [comment]
@eforbes24 If you pull from the dev branch, this should now be fixed.
