### ISSUE TITLE
Import Minian Error - no skimage module

### ISSUE THREAD

**Issue by cjgabrie** [denisecailab/minian#87]
Hi--

I love the package overall. I tried sharing the pipeline with lab mates by installing on a few new computers (PCs, Windows 10). 

When attempting to install the pipeline for the first time on these new PC's, and verifying the installation using "pipeline_noted" notebook, I receive an error when trying to import the minian modules.

I've included an image of the code and error. Can you please advice how to solve this issue?

![minian_skimage_error](https://user-images.githubusercontent.com/25350601/100151600-39664180-2e56-11eb-9255-86d2b446d5e2.png)

**Comment by phildong** [comment]
hopefully the conda-forge package would solve installation problems like this. Check out https://minian.readthedocs.io/en/stable/start_guide/install.html#install-using-conda

Feel free to reopen if you still get installation problems!
