### ISSUE TITLE
wrong params used in second temporal update of pipeline notebook

### ISSUE THREAD

**Issue by joezaki** [denisecailab/minian#93]
![Screen Shot 2020-12-23 at 11 35 55 PM](https://user-images.githubusercontent.com/37089284/103060907-9c431980-4577-11eb-96f5-b1b9885e16cb.png)

The second temporal update of the pipeline uses `param_first_temporal` instead of `param_second_temporal`

**Comment by phildong** [comment]
should be fixed now
