### ISSUE TITLE
Can't save motion correction shifts when nparts is too small

### ISSUE THREAD

**Issue by wmau** [denisecailab/minian#94]
When the `npart` parameter in `estimate_shifts` is too low (<18 for a 20-30 min movie), `save_minian` throws this error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

~/GitHub/minian/minian/utilities.py in save_minian(var, dpath, meta_dict, overwrite, chunks, mem_limit)
    253         except FileNotFoundError:
    254             pass
--> 255     ds.to_zarr(fp, mode=md)
    256     if chunks is not None:
    257         chunks = {d: var.sizes[d] if v <= 0 else v for d, v in chunks.items()}

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/xarray/core/dataset.py in to_zarr(self, store, mode, synchronizer, group, encoding, compute, consolidated, append_dim)
   1614         from ..backends.api import to_zarr
   1615 
-> 1616         return to_zarr(
   1617             self,
   1618             store=store,

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/xarray/backends/api.py in to_zarr(dataset, store, mode, synchronizer, group, encoding, compute, consolidated, append_dim)
   1342     # TODO: figure out how to properly handle unlimited_dims
   1343     dump_to_store(dataset, zstore, writer, encoding=encoding)
-> 1344     writes = writer.sync(compute=compute)
   1345 
   1346     if compute:

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/xarray/backends/common.py in sync(self, compute)
    196             # targets = [dask.delayed(t) for t in self.targets]
    197 
--> 198             delayed_store = da.store(
    199                 self.sources,
    200                 self.targets,

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/dask/array/core.py in store(sources, targets, lock, regions, compute, return_stored, **kwargs)
    912 
    913         if compute:
--> 914             result.compute(**kwargs)
    915             return None
    916         else:

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2593                     should_rejoin = False
   2594             try:
-> 2595                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2596             finally:
   2597                 for f in futures.values():

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1885             else:
   1886                 local_worker = None
-> 1887             return self.sync(
   1888                 self._gather,
   1889                 futures,

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    777             return future
    778         else:
--> 779             return sync(
    780                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    781             )

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    346     if error[0]:
    347         typ, exc, tb = error[0]
--> 348         raise exc.with_traceback(tb)
    349     else:
    350         return result[0]

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/distributed/utils.py in f()
    330             if callback_timeout is not None:
    331                 future = asyncio.wait_for(future, callback_timeout)
--> 332             result[0] = yield future
    333         except Exception as exc:
    334             error[0] = sys.exc_info()

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1750                             exc = CancelledError(key)
   1751                         else:
-> 1752                             raise exception.with_traceback(traceback)
   1753                         raise exc
   1754                     if errors == "skip":

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/dask/optimization.py in __call__()
    980         if not len(args) == len(self.inkeys):
    981             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 982         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
    983 
    984     def __reduce__(self):

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/dask/core.py in get()
    147     for key in toposort(dsk):
    148         task = dsk[key]
--> 149         result = _execute_task(task, cache)
    150         cache[key] = result
    151     result = _execute_task(out, cache)

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/dask/core.py in _execute_task()
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/GitHub/minian/minian/motion_correction.py in est_sh_part()
    116         else:
    117             continue
--> 118         sh_add = match_func(fm, temp, max_sh, local)
    119         for j in sh_idx:
    120             sh_ls[j] = sh_ls[j] + sh_add.reshape((1, -1))

~/GitHub/minian/minian/motion_correction.py in match_temp()
    142         [array]: array (x,y) of the shift (match)
    143     """
--> 144     src = np.pad(src, max_sh)
    145     cor = cv2.matchTemplate(
    146         src.astype(np.float32), dst.astype(np.float32), cv2.TM_CCOEFF_NORMED

<__array_function__ internals> in pad()

/opt/miniconda3/envs/minian-perf/lib/python3.8/site-packages/dask/array/core.py in __array_function__()
   1348         if da_func is func:
   1349             return handle_nonmatching_names(func, args, kwargs)
-> 1350         return da_func(*args, **kwargs)
   1351 
   1352     @property

TypeError: pad() missing 1 required positional argument: 'mode'

**Comment by phildong** [comment]
This should no longer be an issue in latest release.
